### PR TITLE
just fixing a few details

### PR DESCRIPTION
**Pull request by fchapoton**
removing unused imports, some code formatting, etc

most of the change are removing white spaces at the end of lines

should not be controversial, hopefuly

### CODE REVIEW

**Comment by rbommel** [comment]
These changed all look very reasonable, I started to run the tests on them.

**Comment by rbommel** [comment]
One test seems to fail, but I don't think it is anything serious, but maybe @alexjbest can also take a look at it.

**Comment by alexjbest** [comment]
Changes don't seem to do anything objectionable, I'm guessing the test failure is some permission related problem. I've invited @fchapoton as a collaborator in case that helps, but I think I'll just merge anyways and sort it out later if the tests keep fail.

**Comment by alexjbest** [comment]
Indeed looks to work fine when the tests are run from master

**Pull request merged**
